 -- \! clear if you are using windows try \! cls
\! clear
DROP TABLE CORSO_LAUREA CASCADE;
DROP TABLE FACOLTA CASCADE;
DROP TABLE PROPOSTA CASCADE;
DROP TABLE STUDENTE CASCADE;
DROP TABLE INSEGNAMENTO CASCADE;
DROP TABLE MESSAGGIO CASCADE;
DROP TABLE COMMENTO CASCADE;
DROP TABLE SEGUITO CASCADE;




CREATE TABLE CORSO_LAUREA (
	nomeCl VARCHAR(20),
	durata INTEGER NOT NULL,
	tipo VARCHAR(30) NOT NULL,
	PRIMARY KEY(nomeCl)
);


CREATE TABLE FACOLTA (
	nomeF VARCHAR(20) PRIMARY KEY
);

CREATE TABLE PROPOSTA(
	corso_laureaP VARCHAR(20),
	facolta VARCHAR(20),
	FOREIGN KEY(facolta) REFERENCES FACOLTA(nomeF) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY(corso_laureaP) REFERENCES CORSO_LAUREA(nomeCl) ON DELETE NO ACTION ON UPDATE NO ACTION,
	PRIMARY KEY(facolta, corso_laureaP)
);

CREATE TABLE STUDENTE (
	mat VARCHAR(10),
	cog VARCHAR(10) NOT NULL,
	nome VARCHAR(10) NOT NULL,
	uni VARCHAR(20) NOT NULL,
	stato VARCHAR(30) NOT NULL,
	dn DATE NOT NULL,
	login VARCHAR(10) NOT NULL,
	pw VARCHAR(10) NOT NULL,
	corso_laureaS VARCHAR(20) NOT NULL,
	da DATE NOT NULL,
	dr DATE,
	PRIMARY KEY(mat),
	FOREIGN KEY(corso_laureaS) REFERENCES CORSO_LAUREA(nomeCl) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE INSEGNAMENTO (
	cod VARCHAR(10),
	corso_laureaI VARCHAR(20),
	nomeI VARCHAR(30) NOT NULL,
	doc VARCHAR(30) NOT NULL,
	aa VARCHAR(9) NOT NULL,
	PRIMARY KEY(cod),
	FOREIGN KEY(corso_laureaI) REFERENCES  CORSO_LAUREA(nomeCl) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE MESSAGGIO (
	id SERIAL,
	studenteM VARCHAR(10) NOT NULL,
	dataOraM TIMESTAMP NOT NULL,
	oggetto VARCHAR(30) NOT NULL,
	testoM VARCHAR(140) NOT NULL,
	tipologia VARCHAR(20) NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(studenteM) REFERENCES STUDENTE(mat) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE COMMENTO (
	messaggio INTEGER,
	studenteC VARCHAR(10),
	dataOraC TIMESTAMP,
	testoC VARCHAR(140) NOT NULL,
	PRIMARY KEY(messaggio, studenteC, dataOraC),
	FOREIGN KEY(studenteC) REFERENCES STUDENTE(mat) ON DELETE NO ACTION ON UPDATE NO ACTION, 
	FOREIGN KEY(messaggio) REFERENCES MESSAGGIO(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE SEGUITO (
	studenteS VARCHAR(10),
	ins_cod VARCHAR(10),
	PRIMARY KEY(studenteS, ins_cod),
	FOREIGN KEY(studenteS) REFERENCES STUDENTE(mat),
	FOREIGN KEY(ins_cod) REFERENCES INSEGNAMENTO(cod) ON DELETE NO ACTION ON UPDATE NO ACTION
);